In [10]:
##Injecting invalid data for testing

def Modify_df(arg1,arg2,arg3) : # arg1 is df, arg2 is no of rows in df and arg3 is no of columns in df

    for NoofCol in range(arg3) :
        randomlist  = random.sample(range(0, arg2), 3)
        randomlist2 = random.sample(range(0, arg2), 8)
        i = 0
        while i < 3 :
            arg1.iloc[randomlist[i],NoofCol] = np.nan
            i = i+1
    j = 0
    while j < 8:
        arg1.iloc[randomlist2[j],0] = 1
        arg1.iloc[randomlist2[j+1],2] = "a"
        arg1.iloc[randomlist2[j+2],1] = 1
        arg1.iloc[randomlist2[j+3],3] = "a"
        j = j+4
        
    return(arg1)

In [11]:
# 15% rows checked for identifying type of data in columns. 

def idencoltyp(arg1,arg2,arg3) : 
  
    # arg1 is df
    # arg2 is LenDf
    # arg3 is LenCol
    #15% of rows checked but what if length > 10000  
    
    if ((round(15/100)*arg2)%2) == 0 :          # To ensure odd number of rows selected for checking.
        QntytoChk = (round(15/100)*arg2)+1
    else :
        QntytoChk = (round(15/100)*arg2)
        
    ColTyp = []
    for NoofCol in range(arg3) :
        NoofRwChkd = 0
        NoofStr = 0
        NoofNmr = 0
        randomlist = random.sample(range(0, arg2), QntytoChk)
        while NoofRwChkd < QntytoChk :
            RwNo  = randomlist[NoofRwChkd]             
            if type(arg1.iloc[RwNo,NoofCol]) == str :
                NoofStr += 1
            else : 
                NoofNmr += 1
            NoofRwChkd += 1
        if NoofStr > NoofNmr :
            ColTyp.append("Text")
        else :
            ColTyp.append("Numbers")
            
    return(ColTyp)

In [12]:
# for getting row and columns details of each NAN

def Nandet(arg1,arg2,arg3) : 
    
    totNan = 0
    totRC = []
    for noofcol in range(arg3) :
        ColSel = arg2[noofcol]
        NulRws  = (arg1[arg1[ColSel].isnull()].index.tolist())
        NRLen = len(NulRws)
        for NoNul in range(NRLen) :
            totNan += 1
            totRC.append([NulRws[NoNul],noofcol])
    return(totNan,totRC)

In [13]:
# checking for invalid entries(other than NaNs) in text and numeric columns 

def dtavalid (arg1,arg2,arg3,arg4,arg5): # arg1 is list of column names, arg2 is dataframe
     
    df1        = arg1   
    LenDf1     = arg2
    ColNames1  = arg3
    ColTyp     = arg4
    LenCol1    = arg5
    
    Nopbl = True
    
    NaNRC = []
    PrblRCs =[]
    
    (TotNoNaN,TotRC) = Nandet(arg1,arg3,arg5)  # To get RC details of all NaNs.
    
    for noofcol in range(arg5) :
    
        NonStr = 0
        NonNmr = 0  
        NoofNaN = sum(pd.isnull(df1[ColNames1[noofcol]]))   # summing number of Nan in each column.
        for noofrw in range(arg2) :            
            if (arg4[noofcol] == "Text" and type(arg1.iloc[noofrw,noofcol]) != str ) :
                NonStr += 1
                TotRC.append([noofrw,noofcol])
                
            if ColTyp[noofcol] == "Numbers" and type(df1.iloc[noofrw,noofcol]) == str :
                NonNmr += 1
                TotRC.append([noofrw,noofcol])  
                
        if (NonNmr != 0 or NonStr != 0 or NoofNaN != 0) :
            
            Nopbl = False
            print("Column ",ColNames[noofcol]," should have only ",ColTyp[noofcol]+" but also contains")
            if ColTyp[noofcol] == "Text" :
                msg = (str(NonStr)+" Number of Non Strings of which "+str(NoofNaN)+" are NaNs.")            
            if ColTyp[noofcol] == "Numbers" :
                msg = (str(NonNmr)+" Number of Non Numericals and "+str(NoofNaN)+" Number of NaNs.")

            print(msg,'\n')  
            
    if Nopbl == False :
        
        DFDefect = BldDefDF(arg1,TotRC,arg3)  #Building a dataframe having where values are identified as invalid.
        
        print("Total Number of NaNs are :",TotNoNaN,'.  Also check for other wrong entries as mentioned above. \n')
        print("Following is the list of rows where data is not valid and has to be corrected. No of rows presented",len(DFDefect),"of ",LenDf1,".\n\n")
        print(DFDefect)
        print("\n\n Invalid data injected through line 61 of csvtomongodb.py. To stop make inject =  = 'n' \n\n")
        print("Only defective data presented above. Complete including defective data given below, which could guide in rectifying")
        print(df)
        
    return(Nopbl)

In [14]:
#Building a dataframe from original, where values are identified as invalid and a RC list created.

def BldDefDF(arg1,arg2,arg3) : 
    # arg1 df; 
    # arg2 list of RCs  of original DF where data is identified as invalid or NaN
    # arg3 is list of Col names


    RLst = []                       # list containing 'R' values from list of RCs list
    for pshin in range(len(arg2)) :
        RLst.append(arg2[pshin][0])

    Compact_list = []               # After Removing Duplicates from Rlist
    for num in RLst:
        if num not in Compact_list: 
            Compact_list.append(num) 
    Compact_list.sort()
    DFDef = pd.DataFrame(columns = arg3)
    for itno in range(len(Compact_list)) :
        DFDef = DFDef.append(arg1.iloc[Compact_list[itno]])

    return(DFDef)

In [6]:
#changing working directory

def ChngDir() :

    print("Current Working Directory " , os.getcwd())
    contin = "Y"
    while contin == "Y" :
        nwdir = input ("Enter Directory :")
        if os.path.exists(nwdir) :
            os.chdir(nwdir)
            print("Directory changed to ",os.getcwd())
            contin = "n"
        else:
            print(" Working Directory ",nwdir,"  does not exist.")
            contin = (input("Want to continue")).upper()

In [15]:
# checking for availability of file containing data to be analysed.

def FilChk() :
    print("\n\n File will be checked in dir",os.getcwd())
    contin = "Y"
    while contin == "Y" :
        nfile = input ("\n Enter File Name with extension:")
        Flnm = os.getcwd()+"\\"+nfile
        y = os.path.isfile(Flnm)
        if y == True :
            print ("File",Flnm,"is available \n")
            contin = "N"
        else :
            print ("File",Flnm,"is not available\n")
            contin = (input("Want to continue")).upper()
    return(Flnm)

In [9]:
#source to mongod

import pandas as pd
import numpy as np
import pymongo
import json
import csv
import os
import random
import sys

myclient = pymongo.MongoClient("mongodb://localhost:27017/")

ChngDir()
TargetFile = FilChk()

#os.chdir(r'D:\CCE_DA_Project')           # change to directory containg working file

LinRegDB = myclient["LinReg"]            # DB for a group
LinRegIp = LinRegDB["LinReginput"]       # Collection 1 input file
LinREgOp = LinRegDB["LinRegoutput"]      # Collection 2 Results. (single or multiple for different groups)

delinp  = LinRegIp.delete_many({})       #  kept this for testing purposes
delout =  LinREgOp.delete_many({})       #  kept this for testing purposes

#df =pd.read_csv("Automobiles_price_mileage_country.csv")   #  pass name of file thorugh user

if TargetFile[-3:].upper() == "CSV":
    df =pd.read_csv(TargetFile)
    
elif TargetFile[-3:].upper() == "TXT" :
    df = pd.read_csv(TargetFile,delimiter=',')                        # HOW TO TAKE CARE OF OTHER DELIMITERS.

elif TargetFile[-3:].upper() == "XLS" or TargetFile[-4:].upper() == "XLSX"  :
    ShtName = input ("\n Enter Sheet name. If blank first sheet will taken:")
    if len(ShtName) == 0 :
        df = pd.read_excel(TargetFile)
    else :
        df = pd.read_excel(TargetFile,sheet_name = ShtName)
else :
    input("not a suitable file")
    # exit()                                                            # how to break ut.


LenDf = len(df)

ColNames  = []
for col in df.columns: 
    ColNames.append(col)
LenCol = len(ColNames)

ColTypes = idencoltyp(df,LenDf,LenCol)  # for finding out type of data column wise.

print("\nThe  columns in database are  : ", ColNames)     
print("The corresponding types are   : ", ColTypes)
print("Total no of rows are          :  "+str(LenDf)+". \n")


inject = 'y'   # make n to stop.
if inject == "y" :       
    ModDf = Modify_df(df, LenDf, LenCol)  #Injecting invalid data for testing To be  deleted. Presently for testing
    df = ModDf

proceed = dtavalid(df,LenDf,ColNames,ColTypes,LenCol)      #  function for validating data

if proceed == True :  # Ensure there are no null data
    for noofrw in range(LenDf) :
        rw = '{"_id" : ' + str(noofrw+1)
        for noofcol in range(LenCol) :
            rw = rw+', "'+ColNames[noofcol]+'": '
            if type(df.iloc[noofrw,noofcol]) == str :
                rw = rw+'"'+(df.iloc[noofrw,noofcol])+'"'    #  to put quotes if data is a string
            else :                                        
                rw = rw+str(df.iloc[noofrw,noofcol])         # not putting quotes if not a string
        rw = rw+' }'
        rwdict = json.loads(rw)
        x = LinRegIp.insert_one(rwdict)

    for x in LinRegIp.find():
        print(x)
    print(type(LinRegIp))

Current Working Directory  C:\Users\Manjunatha-Think
Enter Directory :C:\Users\Manjunatha-Think
Directory changed to  C:\Users\Manjunatha-Think


 File will be checked in dir C:\Users\Manjunatha-Think

 Enter File Name with extension:testing.xlsx
File C:\Users\Manjunatha-Think\testing.xlsx is available


 Enter Sheet name. If blank first sheet will taken:

The  columns in database are  :  ['Make', 'Country', 'Mileage', 'Price']
The corresponding types are   :  ['Text', 'Text', 'Numbers', 'Numbers']
Total no of rows are          :  45.

Column  Make  should have only  Text but also contains
5 Number of Non Strings of which 3 are NaNs.

Column  Country  should have only  Text but also contains
5 Number of Non Strings of which 3 are NaNs.

Column  Mileage  should have only  Numbers but also contains
2 Number of Non Numericals and 2 Number of NaNs.

Column  Price  should have only  Numbers but also contains
2 Number of Non Numericals and 3 Number of NaNs.

Total Number of NaNs are : 11 .  Also check for other wrong entries as mentioned above.

Following is the list of rows where data is not valid and has to be corrected. No of rows presented 18 of  45 .


                   Make Country Mileage  Price
3      Ford Aerostar V6     NaN      18  12267
5                   NaN   Japan      19  14944
6          Nissan Van 4       1      19  14799
7   Chevrolet Camaro V8       1      20  11545
8                     1   Japan      20  24760
10   Mitsubishi Wagon 4   Japan       a  14929
11      Nissan Axxess 4   Japan     NaN  13949
12  Mitsubishi Sigma V6   Japan      21      a
21       Ford Taurus V6     USA      22    NaN
26    Toyota Cressida 6     NaN      23  21498
30                    1     NaN      25   9599
32                  NaN   Japan      25  10989
35        Dodge Daytona     USA      27    NaN
37          Subaru XT 4   Japan      28      a
39      Mazda Prot_g_ 4   Japan       a   6599
40       Eagle Summit 4     USA      33    NaN
41        Ford Escort 4     USA     NaN   7402
43                  NaN   Japan      34   5866


 Invalid data injected through line 61 of csvtomongodb.py. To stop make inject =  = 'n'


Only defective data presented above. Complete including defective data given below, which could guide in rectifying
                             Make Country Mileage  Price
0            Chevrolet Caprice V8     USA      18  14525
1         Chevrolet Lumina APV V6     USA      18  13995
2          Dodge Grand Caravan V6     USA      18  15395
3                Ford Aerostar V6     NaN      18  12267
4                 Ford Mustang V8     USA      19  12164
5                             NaN   Japan      19  14944
6                    Nissan Van 4       1      19  14799
7             Chevrolet Camaro V8       1      20  11545
8                               1   Japan      20  24760
9      Ford LTD Crown Victoria V8     USA      20  17257
10             Mitsubishi Wagon 4   Japan       a  14929
11                Nissan Axxess 4   Japan     NaN  13949
12            Mitsubishi Sigma V6   Japan      21      a
13               Nissan Santaza 4   Japan      21  11650
14                Buick Century 4     USA      21  13150
15                   Mazda 929 V6   Japan      21  23300
16     Oldsmobile Cutlass Ciera 4     USA      21  13150
17  Oldsmobile Cutlass Supreme V6     USA      21  14495
18        Chrysler Le Baron Coupe     USA      22  12495
19         Chrysler New Yorker V6     USA      22  16342
20               Eagle Premier V6     USA      22  15350
21                 Ford Taurus V6     USA      22    NaN
22               Nissan Maxima V6   Japan      22  17899
23                Buick Skylark 4     USA      23  10565
24            Oldsmobile Calais 4     USA      23   9955
25            Ford Thunderbird V6     USA      23  14980
26              Toyota Cressida 6     NaN      23  21498
27             Buick Le Sabare V6     USA      23  16145
28                 Nissan 240SX 4   Japan      24  13249
29                   Ford Tempo 4     USA      24   9483
30                              1     NaN      25   9599
31           Chrysler Le Baron V6     USA      25  10945
32                            NaN   Japan      25  10989
33                 Plymouth Laser     USA      26  10855
34            Chevrolet Beretta 4     USA      26  10320
35                  Dodge Daytona     USA      27    NaN
36         Honda Prelude Si 4WS 4   Japan      27  13945
37                    Subaru XT 4   Japan      28      a
38                     Ford Probe     USA      30  11470
39                Mazda Prot_g_ 4   Japan       a   6599
40                 Eagle Summit 4     USA      33    NaN
41                  Ford Escort 4     USA     NaN   7402
42           Honda Civic CRX Si 4   Japan      33   9410
43                            NaN   Japan      34   5866
44                Toyota Tercel 4   Japan      35   6488